"""User photo

Revision ID: 715362d591c5
Revises: 1044c08ea4b9
Create Date: 2021-09-17 07:30:20.732197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715362d591c5'
down_revision = '1044c08ea4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_model', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_file_model_url'), ['url'])

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tag_name'), ['name'])

    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_model_username'), ['username'])
        batch_op.create_foreign_key(batch_op.f('fk_user_model_photo_id_file_model'), 'file_model', ['photo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_model_photo_id_file_model'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_user_model_username'), type_='unique')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tag_name'), type_='unique')

    with op.batch_alter_table('file_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_file_model_url'), type_='unique')

    # ### end Alembic commands ###
