"""User is_staff

Revision ID: aad83e2009cc
Revises: 8a984e86b17a
Create Date: 2021-09-08 11:01:39.828818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad83e2009cc'
down_revision = '8a984e86b17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('is_staff', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'is_staff')
    # ### end Alembic commands ###
